name: Publish Docker Image
on:
  release:
    types: [released]
    branches:
      - main
  workflow_dispatch:


jobs:
  build_and_push:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    environment: docker
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Get semantiv version
        run: |
          VERSION=${{ github.ref_name }}
          echo "VERSION=${VERSION#v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        id: push
#        uses: docker/build-push-action@v6
        run: |
          echo ${{ github.repository }}
          echo ${{ github.VERSION }}
          echo ${{ github }}
#        with:
#          context: .
#          file: ./Dockerfile
#          build-args: |
#            SETUPTOOLS_SCM_PRETEND_VERSION: ${VERSION#v}
#          push: true
#          tags: |
#            ${{ github.repository }}:latest
#            ${{ github.repository }}:${VERSION#v}
