name: Publish Docker Image
on:
  release:
    types: [released]
    branches:
      - main
  workflow_dispatch:


jobs:
  build_and_push:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    environment: docker
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Extract version string
        id: version
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> "$GITHUB_OUTPUT"
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            SETUPTOOLS_SCM_PRETEND_VERSION=${{ steps.version.outputs.VERSION }}
          tags: |
            ${{ github.repository }}:latest
            ${{ github.repository }}:${{ steps.version.outputs.VERSION }}
          push: true
