name: Publish Docker Image
on:
  release:
    types: [released]
    branches:
      - main
  workflow_dispatch:


jobs:
  build_and_push:
    name: Build & Push to Docker Hub
    runs-on: ubuntu-latest
    environment: docker
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    env:
      VERSION: ${GITHUB_REF_NAME#m}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
      - name: Build and push Docker image
        id: push
#        uses: docker/build-push-action@v6
        run: |
          echo ${{ github.repository }}
          echo ${{ env.VERSION }}
#        with:
#          context: .
#          file: ./Dockerfile
#          build-args: |
#            SETUPTOOLS_SCM_PRETEND_VERSION: ${VERSION#v}
#          push: true
#          tags: |
#            ${{ github.repository }}:latest
#            ${{ github.repository }}:${VERSION#v}
